### ISSUE TITLE
Error thrown when previous blind test unavailable

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#1]
In user testing it was reported that if there was no previous blind test available, the script could not continue even though this should be an optional parameter.  

suggestion: if the string for prev result is empty, or the string does not resolve to a valid file, fall back to the default action of no previous results after a friendly message to the terminal.

**Comment by victor-zhao-ibm** [comment]
Hi @amchaney,

Could you elaborate this error in detail? In my local setting, when no previous result is available, the script is able to generate the figure with only one precision curve for current classifier.

When the previous test output doesn't conform to the expected format (e.g. not a valid file or not in the expected schema), the script will throw the exception to the console. The user may require to validate the correctness of the file to avoid unnecessary processing time and API charges.

Below is the config file when no previous result is available. 
Notice that the `previous_blind_out` item is removed.

```
[DEFAULT]
; KFOLD, BLIND or TEST
mode = BLIND
intent_train_file = ./data/intent-train.csv
entity_train_file = ./data/entity-train.csv
; Test input file for blind and standard test
test_input_file = ./data/test.csv
; Test output path for blind and test
test_output_path = ./data/test-out.csv
; All temporary files will be stored here
temporary_file_directory = ./data
; Figure path for kfold and blind
out_figure_path= ./data/figure.png
; yes/no
keep_workspace_after_test = no


[ASSISTANT CREDENTIALS]
username = <wa-username>
password = <wa-password>

```

**Comment by amchaney** [comment]
will update README to be more specific about when to include parameters
