### ISSUE TITLE
Ability to specify or carry forward the metadata associated with the WA skill

### ISSUE THREAD

**Issue by victorpovar** [cognitive-catalyst/WA-Testing-Tool#113]
Add the ability to specify within the config file or carry forward the following metadata associated with the WA skill:
- whether the autocorrect feature is turned on/off
- keep default/beta system entities
- turn on/off disambiguation

The above feature will allow a customer to decide which features to turn on/off within their environment.

**Comment by andrewrfreed** [comment]
There is also metadata to handle enhanced irrelevancy detection: `WorkspaceSystemSettingsOffTopic`

**Comment by sueschm** [comment]
These settings are all set as part of the WorkspaceSystemSettings

https://watson-developer-cloud.github.io/swift-sdk/services/AssistantV1/Structs/WorkspaceSystemSettings.html

These settings are passed in on createWorkspace call

**Comment by andrewrfreed** [comment]
Merged
