### ISSUE TITLE
Blind Test not working for NLC

### ISSUE THREAD

**Issue by bharaniabhishek123** [cognitive-catalyst/WA-Testing-Tool#129]
I want run blind test against NLC classifier but got error as "ValueError: Unknown mode 'blind" .

**Comment by andrewrfreed** [comment]
Can you confirm your config.ini line is `mode = blind`  (no quotes present in the line), it looks like your line might be `mode = blind"` or containing some other extra character.

**Comment by andrewrfreed** [comment]
Assumed fixed - please reopen if this is not working.
