### ISSUE TITLE
Deprecation warning on import of watson-developer-cloud

### ISSUE THREAD

**Issue by stefanvds** [cognitive-catalyst/WA-Testing-Tool#131]
A deprecation warning is received when a k-fold analysis is run.

`workspaceParser.py:33: DeprecationWarning: watson-developer-cloud moved to ibm-watson. To get updates, use the new package.`

The import needs to be changed to point to the new `ibm-cloud` version.

**Comment by andrewrfreed** [comment]
@stefanvds I believe this was addressed a few revisions ago:

```
afreed [~/WA-Testing-Tool]$ git pull
Already up to date.
afreed [~/WA-Testing-Tool]$ grep -R watson-developer-cloud *
dialog_test/flowtest.py:        if pkg.key == 'watson-developer-cloud':
afreed [~/WA-Testing-Tool]$ 
```

Nonetheless I have fixed the other reference.  If you disagree please let me know.

**Comment by andrewrfreed** [comment]
Assuming fixed.
