### ISSUE TITLE
Top line of "standard test" results was the utterance "utterance"

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#14]
When running the standard test, the top result (line 2) was the utterance "utterance" and this was not part of the input.

**Comment by victor-zhao-ibm** [comment]
Hi @amchaney. It seems like the bug doesn't occur in the latest commit on master branch. I verified this by running the testing script using car dashboard dataset. What is the commit ID of your local environment?

**Comment by amchaney** [comment]
Hi @victor-zhao-ibm ... i am up to date on origin master.  I will ping you the config file and data file i am using in slack.  i just reran and verified i still see the error

**Comment by victor-zhao-ibm** [comment]
Fixed in #19. MS Excel adds `\ufeff` at the beginning of csv file so that `csv` cannot parse it.
