### ISSUE TITLE
Support Cloud Pak For Data (CP4D) Authentication

### ISSUE THREAD

**Issue by rgeorgi** [cognitive-catalyst/WA-Testing-Tool#175]
Cloud Pak For Data (CP4D) uses a [slightly different authentication mechanism](https://cloud.ibm.com/apidocs/cloud-pak-data#getauthorizationtoken) than the standard IAM Token. This PR adds the [BearerTokenAuthenticator](https://github.com/IBM/python-sdk-core/blob/master/ibm_cloud_sdk_core/authenticators/bearer_token_authenticator.py) from ibm_cloud_sdk_core to support authentication via the user-based bearer token CP4D users can find in their instances' service details page.

I've  add [PR 174](https://github.com/cognitive-catalyst/WA-Testing-Tool/pull/174) that offers a solution for this, adding an `--auth-type` arg to the commandline programs and an `auth_type` key to the `config.ini` file to specify this (non-default) behavior.

**Comment by andrewrfreed** [comment]
PR was merged, thanks for addressing!
