### ISSUE TITLE
Keep getting forbidden error when trying to pull conversational logs

### ISSUE THREAD

**Issue by abhishek-sharma2** [cognitive-catalyst/WA-Testing-Tool#178]
Hi, since 8 January I've been getting the following error when running the getAllLogs command on my Watson workspace. Is anyone else also getting this? I've tested with different instances and workspaces and all of them are throwing the same error:

```
ERROR:root:Forbidden
Traceback (most recent call last):
  File "C:\Users\ABS21\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 228, in send
    raise ApiException(
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403 , X-global-transaction-id: 1618da2a-d436-4aac-ab55-d3ac5d4d9898
Traceback (most recent call last):
  File "getAllLogs.py", line 139, in <module>
    logs    = getLogsInternal(service, ARGS.workspace_id, ARGS.filter, ARGS.page_limit, ARGS.number_of_pages)
  File "getAllLogs.py", line 38, in getLogsInternal
    output = assistant.list_all_logs(sort='-request_timestamp', filter=filter, page_limit=page_size_limit, 
cursor=cursor)
  File "C:\Users\ABS21\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_watson\assistant_v1.py", line 3040, in list_all_logs
    response = self.send(request)
  File "C:\Users\ABS21\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 228, in send
    raise ApiException(
ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403 , X-global-transaction-id: 1618da2a-d436-4aac-ab55-d3ac5d4d9898
```

Based on the forbidden nature of this error, pretty sure it's something to do with permissions but can't figure out exactly what.

**Comment by andrewrfreed** [comment]
@abhishek-sharma2 , I tested a couple assistants and got logs from them.  It looks like you are getting an error from IAM authentication.

If the apikey you are using has not been revoked, it may be time for a dependency upgrade from the base folder. (`pip3 install --upgrade -r requirements.txt`) or explicit upgrade of the two IBM libraries.  For reference here is what I tested with:
```
ibm-cloud-sdk-core        1.7.3
ibm-watson                4.7.1
```

The last thing to check is that you have the URL correct for your assistant(s).  The URL/apikey/workspaceID should all go together.  I have seen sometimes the Watson Assistant tooling show a "stale" apikey or workspace ID when I'm logged onto multiple assistants at the same time.

**Comment by andrewrfreed** [comment]
Have not been able to reproduce, please re-open with additional supporting information if this happens again.
