### ISSUE TITLE
Python Notebook - Section 3 function call typo

### ISSUE THREAD

**Issue by acpang** [cognitive-catalyst/WA-Testing-Tool#180]
A number of cells (11) in Section 3 of the Python notebook are calling the 'copy_python_env_file_to_project_asset' function.  

Although it is commented, when attempting to utilize, it will error because the function is looking for 3 parameters vs 2.
- Current usage of 'copy_python_env_file_to_project_asset' function
![image](https://user-images.githubusercontent.com/36804223/110390857-9d42fd80-8034-11eb-8d96-2ae3f87fd076.png)

- Fix for 'copy_python_env_file_to_project_asset' function
![image](https://user-images.githubusercontent.com/36804223/110391303-4ab61100-8035-11eb-8c87-26842a9bbdeb.png)

**Comment by andrewrfreed** [comment]
Already merged
