### ISSUE TITLE
Python Notebook configured to WA url scheduled for deprecation on May 26, 2021

### ISSUE THREAD

**Issue by acpang** [cognitive-catalyst/WA-Testing-Tool#181]
The Watson API endpoint URLs on 'watsonplatform.net' will be retired and cease to function on May 26, 2021.  There is an open call to update any references to the newer endpoint.

Endpoint change notice:
https://cloud.ibm.com/docs/watson?topic=watson-endpoint-change

- Current configuration
![image](https://user-images.githubusercontent.com/36804223/110392427-e7c57980-8036-11eb-92ba-755bd658d044.png)

- Fix to update url
![image](https://user-images.githubusercontent.com/36804223/110392150-81405b80-8036-11eb-9099-058f0065a73a.png)

**Comment by andrewrfreed** [comment]
Already merged
