### ISSUE TITLE
Connect to Watson cloud using proxy

### ISSUE THREAD

**Issue by lagarwalla** [cognitive-catalyst/WA-Testing-Tool#183]
Is there an easy way to connect to Watson URL using proxy. The customer organisation can connect to URL using proxy,  hence looking for a way to use proxy in the tool.

**Comment by andrewrfreed** [comment]
Lalit, it looks like the Watson SDK lets you pass in proxies:

https://github.com/watson-developer-cloud/python-sdk/issues/681
https://stackoverflow.com/questions/53738472/calling-watson-discovery-api-from-behind-a-http-proxy-server-using-python-sdk

I suggest defining two new `config.ini` proprerties (say, `url_http_proxy` and `url_https_proxy`) and if they are not `None` passing them to the `AssistantV1` constructor in `run.py`.  That looks like it should work.
