### ISSUE TITLE
getAllLogs.py fetched only 1 page

### ISSUE THREAD

**Issue by jgajardo** [cognitive-catalyst/WA-Testing-Tool#189]
we have run the getalllogs command dayly to back up and analyze Watson Assistant logs without problem until July 10th. Later (today) running the same command we only get 1 log page for services with at least 5 pages.

python getAllLogs.py -a xxxxxxxxxxxxxxxxxxxxxxxx -w xxxxxxxxxxxxxxxxxxxxxxxxxx -l https://api.us-east.assistant.watson.cloud.ibm.com -c raw -n 200 -p 500000 -o 30062021-wdc.json -f "response_timestamp>=2021-06-30T00:00:00,response_timestamp<=2021-06-30T23:59:00"

if you want to know de skillid and apikey we don't have problems for shared with you.

Thank you for your help

**Comment by andrewrfreed** [comment]
Can you share the error message or the log output, without your apikey included?

**Comment by jgajardo** [comment]
the command does not return errors, it only reports the following:

Fetched 1 log pages
Writing logs to 3072021-dallas.json

but the service contains more than 1 page.

**Comment by andrewrfreed** [comment]
Do the contents of the first page look good or do they contain an error message?

**Comment by jgajardo** [comment]
updating the api version from 2018-09-20 to 2020-04-01 and using default values for -p and -n switches works fine again.
Thank you!!

**Comment by andrewrfreed** [comment]
Awesome, glad you got it working and thanks for reporting back the solution.

**Comment by jgajardo** [comment]
Hello me again. Another fix:
in extractConversations.py

#       record['dialog_turn_counter']      = log['response']['context']['system']['dialog_turn_counter']
        record['dialog_turn_counter']      = log['request']['context']['system']['dialog_turn_counter']

in line number 73

**Comment by jgajardo** [comment]
Hello. Me again, another fix:

in extractConversations.py
Current line 73:      record['dialog_turn_counter']      = log['response']['context']['system']['dialog_turn_counter']
Fixed Line 73:        record['dialog_turn_counter']      = log['request']['context']['system']['dialog_turn_counter']

Thank you!!

**Comment by andrewrfreed** [comment]
Thanks @jgajardo , another user reported the same issue today, I have addressed in issue #190 / pr #191.
Please `git pull` to get the fix.
