### ISSUE TITLE
Make the URL API an input parameter for all scripts that use a URL

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#20]
As reported from a user email:

The problem is that your configuration parameters don't include the URL of the service. This means that the default of `https://gateway.watsonplatform.net/assistant/api` is used which is fine for all WA instances hosted in US South. However, in other regions the URL of the WA API is different e.g if the instance is based in Germany the URL of the API will be `https://gateway-fra.watsonplatform.net/assistant/api` and unless you give users a way to specify this they wont be able to use their code.

Solution would be add the URL to the config file, and pass it as an input parameter to all scripts that call the API

**Comment by victor-zhao-ibm** [comment]
#21
