### ISSUE TITLE
Support for new Actions assistants

### ISSUE THREAD

**Issue by andrewrfreed** [cognitive-catalyst/WA-Testing-Tool#215]
Need to update tool or confirm it works well for Action-based assistants, not just Dialog-based.

**Comment by leighawilliamson** [comment]
Many customers use this library of python functions inside notebooks that extract conversation logs and perform various analytics on the extracted log data. None of those customers are going to move to the New Watson Assistant until these functions work with the New WA. Here are some examples of such customer accounts: City of Austin, San Antonio Metro, State of Louisiana, State of Texas Veterans Land Board, DFW Airport, and more. This issue should have a high priority.

**Comment by kevin2107** [comment]
I agree, we don't have actions in sight

**Comment by andrewrfreed** [comment]
@leighawilliamson @kevin2107 please note both capabilities (logs #227 and blind test #224 ) are addressed, see linked pull requests.

Thanks to many for review and help especially @lmazzoli who helped drive logs to completion.
