### ISSUE TITLE
Does the WA Testing Tool support Watson Assistant API version 2?

### ISSUE THREAD

**Issue by thomassuedbroecker** [cognitive-catalyst/WA-Testing-Tool#222]
In the [config.ini.sample](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/config.ini.sample) only the **Watson Assistant API version 1** is mentioned.

Does the WA Testing Tool support Watson Assistant API version 2?

Information written in the  [config.ini.sample](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/config.ini.sample)  file.

```
; Regardless of mode you must specify a WA environment to test the classification against.
; Update the url for the WA API to match your specific WA region
; url patterns are found at https://cloud.ibm.com/apidocs/assistant/assistant-v1#service-endpoint
url = https://gateway.watsonplatform.net/assistant/api
; if above auth_type is 'bearer' then the iam_apikey will be
; interpreted as a bearer token instead. Put your bearer token below
```

**Comment by andrewrfreed** [comment]
Hi @thomassuedbroecker , we are aware of need to refresh and update for v2, it is not done yet.
