### ISSUE TITLE
implement a partial credit score system

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#25]
Given a input file for a partial credit intent scoring mapping that has the following 3 columns, where a golden intent can be on more than one line:
```
Golden Intent | Partial Credit Intent | Partial Credit Intent score
```
Where `Golden Intent` is an intent from your WA, and `Partial Credit Intent` is another intent in your WA that when served in place of the `Golden Intent` is going to be give partial credit for being correct, and the partial credit (in the range [0,1]) is in the column `Partial Credit Intent score`
Change the scoring of the 
  - Add the partial credit mapping file as an optional parameter to `run.py`
  - [Intent Metrics](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/utils/intentmetrics.py) to use accept the partial credit table as an optional parameter to calculate TPR and PPV 
  - Add a column to the Schema of Results after [yes/no](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/createPrecisionCurve.py#L48) for test output, called score that is a numeric value between [0,1] that is created with the partial credit table, if no partial credit table then the values are just 1 and 0.  
  - [Precision Curve](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/createPrecisionCurve.py#L119) and [here](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/createPrecisionCurve.py#L130) change correct from being the count of `yes` to be the sum of the scores (scores are [0,1])

**Comment by victor-zhao-ibm** [comment]
#26

**Comment by amchaney** [comment]
The only reason i don't close this, is because I need to document it
