### ISSUE TITLE
Intent metrics miscounts number of samples if intent empty

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#27]
@victor-zhao-ibm ... similar to the internal bug, but this one in the [intent metrics](https://github.com/cognitive-catalyst/WA-Testing-Tool/blob/master/utils/intentmetrics.py) file

**Comment by victor-zhao-ibm** [comment]
It is fixed in the latest commit of #26 . Instead of modifying the intent metrics generation script, the workspaceParser.py will filter any intent with empty example list.
