### ISSUE TITLE
Provide confusion matrix

### ISSUE THREAD

**Issue by andrewrfreed** [cognitive-catalyst/WA-Testing-Tool#29]
Build a confusion matrix, either per fold or as summary of all folds.
This helps quickly identify poorly-performing intents and those intents that get confused for each other.

**Comment by amchaney** [comment]
per discussion w/alex format would toggle from a dynamic list with the intent names, like:
```
intent1, # of classifications, confused_intent1, # number of confusions, .... 
...
```
or a csv with a matrix that has all the intents as rows/cols and the matrix is numeric with the diagnal being the correct classifications

**Comment by andrewrfreed** [comment]
Merged!
