### ISSUE TITLE
Update code to support 2.0+ version of watson-developer-cloud SDK

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#30]
Had to force requirements.txt to use wdc 1.3.5 because the 2.0 release changed the signatures of the calls.  Best thing to do here is update our code to use the latest SDK, so adding a ticket to remind us to do that

**Comment by andrewrfreed** [comment]
+1.  On my Watson Assistant project we updated all of the other scripts, tooling, etc to use latest SDKs.  We set aside a separate environment to run this k-folds tester.

**Comment by andrewrfreed** [comment]
This functionality is merged in
