### ISSUE TITLE
Support Token-based Identity and Access Management (IAM) authentication

### ISSUE THREAD

**Issue by cjacobs-ibm** [cognitive-catalyst/WA-Testing-Tool#33]
Per WA release notes, the authentication method will be changing for new services instances created on or after 10/30/18:

"API authentication changes
On 30 October 2018, the US South and Germany regions will transition from using Cloud Foundry to using token-based Identity and Access Management (IAM) authentication. (See Authenticating with IAM tokens External link icon for more information.)

The method used to authenticate with IAM service instances is different from the method used to authenticate with Cloud Foundry instances. Existing applications that use Cloud Foundry will continue to work. However, if you migrate a service instance or create a new service instance in a region that uses IAM, you must update the code that handles authentication. All regions are transitioning to IAM, but on a rolling schedule. For more details, see Data centers."

**Comment by amchaney** [comment]
@victor-zhao-ibm ... Anuj may reach out for some guidance if you have some free time 😸

**Comment by andrewrfreed** [comment]
Delivered in #37
