### ISSUE TITLE
Keep the y-axis constant 0.0-1.0 in precision curve

### ISSUE THREAD

**Issue by victorpovar** [cognitive-catalyst/WA-Testing-Tool#41]
Add the y-axis parameter to createPrecisionCurve script in order to keep the y-axis constant. Additionally, expose the value for the y-axis parameter within the config file.

**Comment by andrewrfreed** [comment]
Let's not expose to config file unless absolutely necessary, we should not overburden users with config requirements if there are sensible defaults we can use.

**Comment by victorpovar** [comment]
The background here is that the client wanted to keep the y-axis consistent between experiments, such that it is easy to compare results. They planned to run experiments on a weekly basis and the y-axis currently changes dynamically based on the experiment results so the changes are not as obvious when the graphs are put side by side on a PPT slide.

**Comment by andrewrfreed** [comment]
Thanks Victor, that makes sense, I am not sure though why we would not just hardcode 0.0 - 1.0 as the scale.

**Comment by victorpovar** [comment]
I mean we could, but currently the graph is "zoomed in" around the data, so one chart might go from .6 to 1 and another chart might be .7 to 1, so it makes hard to compare these charts as we progress through the project without a way to keep the lower bound to a constant value.

**Comment by victorpovar** [comment]
I got no concerns about hardcoding this to 0.0 to 1.0.

**Comment by andrewrfreed** [comment]
Thanks for the discussion Victor.  Feeling much better about the direction now.  I've viewed the zooming as a bug, not a feature, having to explain why a 0.85 looks so "bad" on a chart!

**Comment by andrewrfreed** [comment]
Merged
