### ISSUE TITLE
Mark a WA confidence score as a * on the Precsion plots

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#5]
Currently, the default WA confidence score to fallback on "I don't know" is 0.2.  Add this threshold value to your config settings as the variable "tau", and indicate on all of the precision test results at what point on the curve corresponds to the "tau" confidence score. Indicate with a `*` or `o` on the line, clear enough to distinguish and put the value of tau in the legend.

**Comment by victor-zhao-ibm** [comment]
Feature is completed.
