### ISSUE TITLE
'ASSISTANT CREDENTIALS' is missing in config file

### ISSUE THREAD

**Issue by ayeshasa** [cognitive-catalyst/WA-Testing-Tool#68]
I keep getting this error even though assistant credentials is in the config file 

'ASSISTANT CREDENTIALS' is missing in config file

**Comment by amchaney** [comment]
hmm, could you tell me how your were invoking the `run.py` script on the command line?

**Comment by ayeshasa** [comment]
Like this:
python run.py -c Users/asaleem/Downloads/WA-Testing-Tool-master/config.ini
Traceback (most recent call last):
  File "run.py", line 552, in <module>
    func(ARGS)
  File "run.py", line 420, in func
    "Section '{}' is missing in config file".format(WCS_CREDS_SECTION))
ValueError: Section 'ASSISTANT CREDENTIALS' is missing in config file

**Comment by andrewrfreed** [comment]
@ayeshasa did that solve your issue?

**Comment by andrewrfreed** [comment]
Assuming this is fixed.
