### ISSUE TITLE
Feature Request: Per intent metrics on True Positive/False Positives

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/WA-Testing-Tool#8]
A user request was submitted to calculate the following per intent metrics given the results of the k-fold-union or a golden (or blind) set:

  - intent name
  - intent true positive rate  = TP/(TP+FN)
  - intent positive predictive value = TP/(TP +FP)
  - intent number of samples (relevant elements)

Using the definitions [here](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)

I think we could add this as another sub-directory, like the intent descriptions, that would just contain a simple python script that inputs the "out" file from the k-fold or golden test, and outputs the per-intent metrics above in a csv.

**Comment by victor-zhao-ibm** [comment]
#23
