### ISSUE TITLE
Expose the version variable to config file

### ISSUE THREAD

**Issue by ajainghub** [cognitive-catalyst/WA-Testing-Tool#86]
The API version used in the API calls is coded in utils/__ init__.py

WCS_VERSION = '2018-07-10'

As a workaround the users can edit the  __ init__.py and change the WCS_VERSION variable but they may forget or not know about it.

Ideally this should be exposed to the config files so that users and match/configure the testing version with the same version they use in their application

**Comment by andrewrfreed** [comment]
See linked commits for how this was addressed.  I implemented two issues in the same pull request as they were easily implemented and tested together.

**Comment by andrewrfreed** [comment]
Merged
