### ISSUE TITLE
Add capability to run the tool from Watson Studio - Python Notebook

### ISSUE THREAD

**Issue by ajainghub** [cognitive-catalyst/WA-Testing-Tool#87]
Need the capability so that users can run this tool from Watson Studio using Python Notebook. The test result files can be exported (if needed) and/or  analyzed in the Notebook itself.

**Comment by ajainghub** [comment]
Working on this. Created a new branch "87_notebook_ws" to add develop and test this capability.

**Comment by andrewrfreed** [comment]
Addressed in PR #97
